version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:3.12.12-management
    container_name: rabbitmq
    deploy:
      resources:
        limits:
          memory: 256m
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: d418ae373cad
    volumes:
      - "rabbitmq_data:/var/lib/rabbitmq"
    networks:
      net:
        aliases:
          - rabbitmq

  redis:
    image: redis:6.2.14
    container_name: redis
    deploy:
      resources:
        limits:
          memory: 128m
    ports:
      - "6379:6379"
    command: redis-server --requirepass ac1c24ef3149
    volumes:
      - "redis_data:/data"
    networks:
      net:
        aliases:
          - redis

  fastapi:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile-local
    container_name: fastapi
    deploy:
      resources:
        limits:
          memory: 128m
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    environment:
      APP_ENV: local_docker
      WATCHFILES_FORCE_POLLING: true
    ports:
      - "8000:8000"
    volumes:
      - ./app:/code/app
    networks:
      net:
        aliases:
          - fastapi
    depends_on:
      - rabbitmq
      - redis

  celery:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile-local
    container_name: celery
    deploy:
      resources:
        limits:
          memory: 128m
    command: celery -A app.worker.celery_worker worker -Q task_queue,celery -l DEBUG
    environment:
      APP_ENV: local_docker
    volumes:
      - ./app:/code/app
    networks:
      net:
        aliases:
          - celery
    depends_on:
      - rabbitmq
      - redis

  flower:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile-local
    container_name: flower
    deploy:
      resources:
        limits:
          memory: 128m
    command: celery -A app.worker.celery_worker flower --broker_api="http://admin:d418ae373cad@rabbitmq:15672/api/" --logging="DEBUG"
    environment:
      APP_ENV: local_docker
    ports:
      - "5555:5555"
    volumes:
      - ./app:/code/app
    networks:
      net:
        aliases:
          - flower
    depends_on:
      - rabbitmq
      - redis

volumes:
  rabbitmq_data:
    driver: local
  redis_data:
    driver: local

networks:
  net:
    driver: bridge